version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: npm start
    tty: true
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports: 
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment: 
      NODE_ENV: production
      DATABASE_URL: "postgres://${DB_USER}:${DB_PASSWORD}@postgres:${DB_PORT}/${DB_DATABASE}"
  postgres:
    image: postgres
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d/
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped
    ports: 
      - ${HOST_DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}

volumes:
  postgres:
    driver: local